### ISSUE TITLE
qmca error

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#2217]
Need help. On my desktop ubuntu 18.04.
```
$ qmca -q ev dmc-a256-e3072-cpu-XL-batch-w7/NiO-fcc-S64-dmc.s003.scalar.dat
Traceback (most recent call last):
  File "/home/yeluo/opt/qmcpack/nexus/bin/qmca", line 29, in <module>
    generic = import_nexus_module('generic')
  File "/home/yeluo/opt/qmcpack/nexus/bin/qmca", line 19, in import_nexus_module
    return importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 888, in get_code
  File "<frozen importlib._bootstrap_external>", line 455, in _validate_bytecode_header
ImportError: bad magic number in 'generic': b'\x03\xf3\r\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yeluo/opt/qmcpack/nexus/bin/qmca", line 49, in <module>
    from generic import obj
ImportError: bad magic number in 'generic': b'\x03\xf3\r\n'
```

**Comment by jtkrogel** [comment]
Please post a reproducer.

**Comment by ye-luo** [comment]
Fix the problem by
1. remove all the .pyc file under nexus. Then the new error indicates missing numpy.
2. install numpy and the error is gone.
