### ISSUE TITLE
Exception handling causes MPI hanging

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#2247]
When I introduced a bug in the code, the exception handling tricks me.
What I don't understand is why the throw from #17 triggers #10 
The node hanging is understandable, #10 is for normal termination of the program and calls darshan to finallize I/O statistics. Because there is only one rank terminating and other ranks wait on a different barrier. The code hangs.
```
(gdb) bt
#0  0x000020001f3316c8 in mlx5_poll_cq_ex_1 () from /lib64/libmlx5-rdmav2.so
#1  0x000020001e92ae24 in PAMI::Device::IBV::Device::advance() () from /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-3/spectrum-mpi-10.3.0.1-20190611-aqjt3jo53mogrrhcrd2iufr435azcaha/lib/pami_port/libpami.so.3
#2  0x000020001e8d86fc in PAMI_Context_advancev () from /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-3/spectrum-mpi-10.3.0.1-20190611-aqjt3jo53mogrrhcrd2iufr435azcaha/lib/pami_port/libpami.so.3
#3  0x000020001ef27624 in LIBCOLL_Advance_pami (context=<optimized out>) at api.cc:87
#4  0x000020001ef218d8 in LIBCOLL_Advance (ctxt=<optimized out>) at libcoll.cc:133
#5  0x000020001ee2cd58 in start_libcoll_blocking_collective () from /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-3/spectrum-mpi-10.3.0.1-20190611-aqjt3jo53mogrrhcrd2iufr435azcaha/lib/spectrum_mpi/mca_coll_ibm.so
#6  0x000020001ee316d4 in mca_coll_ibm_barrier () from /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-3/spectrum-mpi-10.3.0.1-20190611-aqjt3jo53mogrrhcrd2iufr435azcaha/lib/spectrum_mpi/mca_coll_ibm.so
#7  0x000020001346352c in PMPI_Barrier () from /opt/ibm/spectrum_mpi/jsm_pmix/../lib/libmpi_ibm.so.3
#8  0x0000200000079ca8 in darshan_core_shutdown () at ../darshan-runtime/lib/darshan-core.c:375
#9  0x0000200000077454 in MPI_Finalize () at ../darshan-runtime/lib/darshan-core-init-finalize.c:82
#10 0x00000000100608d4 in boost::mpi3::environment::~environment() ()
#11 0x0000200013870df0 in ?? () from /sw/summit/xl/16.1.1-3/lib/libibmc++.so.1
#12 0x00002000138710dc in __IBMCPlusPlusExceptionBase () from /sw/summit/xl/16.1.1-3/lib/libibmc++.so.1
#13 0x00002000138712d8 in __IBMCPlusPlusExceptionV3 () from /sw/summit/xl/16.1.1-3/lib/libibmc++.so.1
#14 0x0000200013a3c2c0 in ?? () from /lib64/libgcc_s.so.1
#15 0x0000200013a3cc20 in _Unwind_RaiseException () from /lib64/libgcc_s.so.1
#16 0x00000000113134fc in __cxxabiv1::__cxa_throw (obj=0x9e7d3a40, tinfo=0x1180c0d8 <typeinfo for std::runtime_error>, dest=0x1131ce10 <std::runtime_error::~runtime_error()>) at /sw/summit/gcc/6.4.0/src/gcc-6.4.0/libstdc++-v3/libsupc++/eh_throw.cc:82
#17 0x00000000101cf730 in void qmcplusplus::TasksOneToOne<(qmcplusplus::Threading)0>::operator()<void (&)(int, qmcplusplus::DMCBatched::StateForThread const&, qmcplusplus::QMCDriverNew::DriverTimers&, std::vector<std::unique_ptr<qmcplusplus::ContextForSteps, std::default_delete<qmcplusplus::ContextForSteps> >, std::allocator<std::unique_ptr<qmcplusplus::ContextForSteps, std::default_delete<qmcplusplus::ContextForSteps> > > >&, std::vector<std::unique_ptr<qmcplusplus::Crowd, std::default_delete<qmcplusplus::Crowd> >, std::allocator<std::unique_ptr<qmcplusplus::Crowd, std::default_delete<qmcplusplus::Crowd> > > >&), qmcplusplus::DMCBatched::StateForThread&, qmcplusplus::QMCDriverNew::DriverTimers&, std::reference_wrapper<std::vector<std::unique_ptr<qmcplusplus::ContextForSteps, std::default_delete<qmcplusplus::ContextForSteps> >, std::allocator<std::unique_ptr<qmcplusplus::ContextForSteps, std::default_delete<qmcplusplus::ContextForSteps> > > > >, std::reference_wrapper<std::vector<std::unique_ptr<qmcplusplus::Crowd, std::default_delete<qmcplusplus::Crowd> >, std::allocator<std::unique_ptr<qmcplusplus::Crowd, std::default_delete<qmcplusplus::Crowd> > > > > >(void (&)(int, qmcplusplus::DMCBatched::StateForThread const&, qmcplusplus::QMCDriverNew::DriverTimers&, std::vector<std::unique_ptr<qmcplusplus::ContextForSteps, std::default_delete<qmcplusplus::ContextForSteps> >, std::allocator<std::unique_ptr<qmcplusplus::ContextForSteps, std::default_delete<qmcplusplus::ContextForSteps> > > >&, std::vector<std::unique_ptr<qmcplusplus::Crowd, std::default_delete<qmcplusplus::Crowd> >, std::allocator<std::unique_ptr<qmcplusplus::Crowd, std::default_delete<qmcplusplus::Crowd> > > >&), qmcplusplus::DMCBatched::StateForThread&, qmcplusplus::QMCDriverNew::DriverTimers&, std::reference_wrapper<std::vector<std::unique_ptr<qmcplusplus::ContextForSteps, std::default_delete<qmcplusplus::ContextForSteps> >, std::allocator<std::unique_ptr<qmcplusplus::ContextForSteps, std::default_delete<qmcplusplus::ContextForSteps> > > > >&&, std::reference_wrapper<std::vector<std::unique_ptr<qmcplusplus::Crowd, std::default_delete<qmcplusplus::Crowd> >, std::allocator<std::unique_ptr<qmcplusplus::Crowd, std::default_delete<qmcplusplus::Crowd> > > > >&&) ()
#18 0x00000000101ce764 in qmcplusplus::DMCBatched::run() ()
#19 0x0000000010093bb0 in qmcplusplus::QMCMain::runQMC(_xmlNode*, bool) ()
#20 0x00000000100931b0 in qmcplusplus::QMCMain::executeQMCSection(_xmlNode*, bool) ()
#21 0x000000001009182c in qmcplusplus::QMCMain::execute() ()
#22 0x000000001005fd8c in main ()
```

**Comment by prckent** [comment]
Does this problem occur without darshan?

We need exceptions to successfully bring down all MPI tasks to avoid wasted supercomputer time. Is this a Summit only issue or more general? I thought we checked this as a condition of using exceptions.

**Comment by ye-luo** [comment]
I didn't try unloading darshan. It can be a workaround but not a fix.
I think it is our problem ending the execution at MPI_Finalize instead of MPI_Abort.
MPI_Finalize in most MPI implementation is an intercepting layer and computer centres can inject anything they need.

**Comment by PDoakORNL** [comment]
I have seen this as of last week while debugging MPI.  I will look at it tonight/tomorrow.  I'm not sure its due to missing MPI_ABORT unless our APP_ABORT macro only calls MPI_FINALIZE.  I have not seen it except with spectrum MPI so far.

**Comment by ye-luo** [comment]
Our APP_ABORT calls MPI_ABORT.

**Comment by prckent** [comment]
All terminating exceptions should call MPI_ABORT.
