### ISSUE TITLE
AFMC methane back propagation / converter test is failing

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#2976]
**Describe the bug**

https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=converter_test_qmcpack_obs_06-methane_converge_back_prop&date=2021-03-02

We haven't been running this test very often, but it has not passed in the last month.

Values are not dramatically off, but "something has changed".

**To Reproduce**

Latest develop version

ctest -R  converter_test_qmcpack_obs_06-methane_converge_back_prop 

Specific build details as per cdash link.

**Expected behavior**

Test should pass.

**System:**

nitrogen and sulfur, nightly gcc+mkl complex builds.

**Comment by Paul-St-Young** [comment]
When was the last time this test passed?
I went back to 3.10.0 and saw similar failures.
Going further back to 3.9.2 and the test is not fully setup.
```
FFF
======================================================================
FAIL: test_average (__main__.TestRDM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "reference/test_obs.py", line 16, in test_average
    self.assertAlmostEqual(2*numpy.sum(rdm_av.real), 9.990239713872079)
AssertionError: 9.999137488227163 != 9.990239713872079 within 7 places (0.00889777435508421 difference)

======================================================================
FAIL: test_extract (__main__.TestRDM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "reference/test_obs.py", line 24, in test_extract
    self.assertAlmostEqual(numpy.sum(dm.real), 499.49878268185375)
AssertionError: 499.78447803686277 != 499.49878268185375 within 7 places (0.2856953550090111 difference)

======================================================================
FAIL: test_extract_single (__main__.TestRDM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "reference/test_obs.py", line 31, in test_extract_single
    self.assertAlmostEqual(numpy.sum(dm).real, 5.00103256421043)
AssertionError: 4.985894261356273 != 5.00103256421043 within 7 places (0.015138302854157182 difference)

----------------------------------------------------------------------
Ran 3 tests in 0.119s

FAILED (failures=3)
```

**Comment by prckent** [comment]
We haven't been running the consistently in the nightlies (python dependencies issues) so I am not sure. Probably best to bisect.
