### ISSUE TITLE
Memory leaks/asan failures in ppconvert 

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#3491]
**Describe the bug**

In #3489  we can see that all the asan failures currently reported are all related to XML handling and the writing of XML. I suspect that some similar cleanup to what has been done in QMCPACK will fix all these problems. With luck there are ohnly a few related to string lifetime, fixable with e.g. some smart pointers or simply deallocating the strings appropriately. This would allow us to run ppconvert in CI and gain >1% coverage.

```
Direct leak of 120 byte(s) in 1 object(s) allocated from:
    #0 0x4c6f0d in operator new(unsigned long) (/__w/qmcpack/qmcpack-build/src/QMCTools/ppconvert/src/ppconvert+0x4c6f0d)
    #1 0x4d3af2 in XMLWriterClass::StartElement(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /__w/qmcpack/qmcpack/src/QMCTools/ppconvert/src/XMLWriterClass2.cc:153:22
    #2 0x4fc664 in PseudoClass::WriteXML(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /__w/qmcpack/qmcpack/src/QMCTools/ppconvert/src/NLPPClass.cc:494:10
    #3 0x531272 in main /__w/qmcpack/qmcpack/src/QMCTools/ppconvert/src/NLPPClass.cc:2013:10
    #4 0x7f7c261320b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
```

**To Reproduce**

Run ppconvert tests with asan

**Expected behavior**

Properly written code should not leak memory and should pass asan

**System:**

CI

**Additional context**

**Comment by ye-luo** [comment]
Has this been resolved?
