### ISSUE TITLE
Faile to execute convert_vp_format.py

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3679]
**Describe the bug**
CMake succeeds but with python error.

```
Traceback (most recent call last):
  File "/home/yeluo/opt/cleanup/qmcpack/tests/molecules/He_param/convert_vp_format.py", line 211, in <module>
    convert_from_text_to_hdf(fname_in, fname_out, args.complex)
  File "/home/yeluo/opt/cleanup/qmcpack/tests/molecules/He_param/convert_vp_format.py", line 179, in convert_from_text_to_hdf
    write_to_hdf(vp, fname_out, output_complex)
  File "/home/yeluo/opt/cleanup/qmcpack/tests/molecules/He_param/convert_vp_format.py", line 163, in write_to_hdf
    f.create_dataset("timestamp",data=[vp.timestamp])
  File "/usr/lib/python3/dist-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/usr/lib/python3/dist-packages/h5py/_hl/dataset.py", line 118, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1634, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1656, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1717, in h5py.h5t.py_create
TypeError: No conversion path for dtype: dtype('<U23')
```

**To Reproduce**
It is on my workstation. No idea what happens.

**Expected behavior**
Pass.

**System:**
 - Epyc server.

**Additional context**
`execute_process(COMMAND` needs to check return code and takes action.

**Comment by markdewing** [comment]
I suspect it's a locale issue.
Could you try this change
```diff
-    f.create_dataset("timestamp",data=[vp.timestamp])
+    f.create_dataset("timestamp",data=[vp.timestamp],dtype=h5py.string_dtype('ascii'))
```

**Comment by ye-luo** [comment]
Unfortunately, it doesn't help. I double checked that the modified line and it does get hit.

**Comment by markdewing** [comment]
What version of h5py and python are you running?
The Numpy U type is a UTF-32 fixed width format (the '23' part is probably the length of the string)
https://docs.h5py.org/en/latest/strings.html

**Comment by markdewing** [comment]
I can reproduce the issue if the data is converted to numpy array first
```
a = np.array([vp.timestamp])
f.create_dataset("timestamp",data=a)
```

**Comment by ye-luo** [comment]
Ubuntu 20.04 python3-h5py 2.10.0

**Comment by markdewing** [comment]
Converting to a numpy array with the 'np.object' type seems to work
```
f.create_dataset("timestamp", data=np.array([vp.timestamp], dtype=np.object))
```

**Comment by ye-luo** [comment]
Got no luck.
```
Traceback (most recent call last):
  File "/home/yeluo/opt/qmcpack/tests/molecules/He_param/convert_vp_format.py", line 211, in <module>
    convert_from_text_to_hdf(fname_in, fname_out, args.complex)
  File "/home/yeluo/opt/qmcpack/tests/molecules/He_param/convert_vp_format.py", line 179, in convert_from_text_to_hdf
    write_to_hdf(vp, fname_out, output_complex)
  File "/home/yeluo/opt/qmcpack/tests/molecules/He_param/convert_vp_format.py", line 163, in write_to_hdf
    f.create_dataset("timestamp", data=np.array([vp.timestamp], dtype=np.object))
  File "/usr/lib/python3/dist-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/usr/lib/python3/dist-packages/h5py/_hl/dataset.py", line 118, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1634, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1656, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1711, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```
