### ISSUE TITLE
qmca fails with: ModuleNotFoundError: No module named 'versions'

### ISSUE THREAD

**Issue by yurivict** [QMCPACK/qmcpack#3884]
```
$ qmca H2O.s002.scalar.dat
Traceback (most recent call last):
  File "/usr/local/bin/qmca", line 29, in <module>
    versions = import_nexus_module('versions')
  File "/usr/local/bin/qmca", line 19, in import_nexus_module
    return importlib.import_module(module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'versions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/qmca", line 53, in <module>
    from versions import nexus_version
ModuleNotFoundError: No module named 'versions'
```

qmcpack-3.13.0

**Comment by yurivict** [comment]
Attn @prckent since you closed the previous issue https://github.com/QMCPACK/qmcpack/issues/1017.

**Comment by jtkrogel** [comment]
Hi @yurivict,

`qmca` is designed to work under if either of the two conditions are met:

1. `qmca` resides in its original directory tree under `qmcpack/nexus/bin`
2. Nexus has been installed by adding `qmcpack/nexus/lib` to `PYTHONPATH`.

The first exception you are seeing relates to (1) above.  The second is related to (2) above.  If you are meeting either condition, then a fix is warranted.  Thanks.

**Comment by yurivict** [comment]
@jtkrogel 

Why aren't python libs installed as part of the 'install' target?

**Comment by brockdyer03** [comment]
Closing since `versions.py` was removed in #5947 and missing imports were handled in #5851.
