### ISSUE TITLE
Library paths in qmcpack.settings are different from pre-specified in the build script

### ISSUE THREAD

**Issue by YanyongW91** [QMCPACK/qmcpack#4577]
hi, developers,
here is my **cmake script**:

```
#!/bin/bash
CC=/home/ywang/code/openmpi-4.1.5ing/bin/mpicc
CXX=/home/ywang/code/openmpi-4.1.5ing/bin/mpicxx
MKL_ROOT=/opt/intel/oneapi/mkl/2021.2.0/
HDF5_ROOT=/home/ywang/code/hdf5-1.14.0/hdf5
BOOST_ROOT=/home/ywang/code/boost_1_82_0
FFTW_HOME=/home/ywang/code/fftw-3.3.10ing
cd build_gnu 
cmake -D CMAKE_C_COMPILER=$CC -D CMAKE_CXX_COMPILER=$CXX ..
make
```
here is the resulting **qmcpack.settings**
```
#qmcpack variables
QMCPACK_VERSION    = 3.16.0
# See qmcpack --version for the most up-to-date information about the
# most recent git commit

QMC_MPI                = ON
QMC_OMP                = ON
QMC_CUDA               = OFF
QMC_COMPLEX            = OFF
QMC_MIXED_PRECISION    = OFF
QMC_SIMD_ALIGNMENT     = 32
BUILD_AFQMC            = OFF
BUILD_FCIQMC           = OFF
ENABLE_OFFLOAD         = OFF
ENABLE_CUDA            = OFF
QMC_CUDA2HIP           = OFF
ENABLE_CUDA            = OFF
ENABLE_PHDF5           = OFF
ENABLE_MASS            =
ENABLE_STACKTRACE      = OFF

#system variables
QMC_HOSTNAME           = panghu
SYSTEM                 = Linux-4.18.0-240.15.1.el8_3.x86_64
SYSTEM_NAME            = Linux
SYSTEM_PROCESSOR       = x86_64
SYSTEM_VERSION         = 4.18.0-240.15.1.el8_3.x86_64
CMAKE_VERSION          = 3.25.3
CMAKE_BUILD_TYPE       = RELEASE

CXX_COMPILER           = /home/ywang/code/openmpi-4.1.5ing/bin/mpicxx
CXX_COMPILER_ID        = GNU
CXX_COMPILER_VERSION   = 9.5.0
CXX_FLAGS              =  -fopenmp -foffload=disable -finline-limit=1000 -fstrict-aliasing -funroll-all-loops -Wno-deprecated -Wvla -Wcomment -Wmisleading-indentation -Wmaybe-uninitialized -Wuninitialized -Wreorder -Wno-unknown-pragmas -Wno-sign-compare -Wsuggest-override -ffast-math -march=native

C_COMPILER             = /home/ywang/code/openmpi-4.1.5ing/bin/mpicc
C_COMPILER_ID          = GNU
C_COMPILER_VERSION     = 9.5.0
C_FLAGS                =  -fopenmp -finline-limit=1000 -fstrict-aliasing -funroll-all-loops -Wno-deprecated -Werror=vla -ffast-math -march=native

CUDA_VERSION           =
CUDA_FLAGS             =

LAPACK_LIBRARIES       = /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_intel_lp64.so;/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sequential.so;/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so;-lm;-ldl;-lm;-ldl
HDF5_INCLUDE_DIR       = /opt/intel/oneapi/intelpython/latest/include
HDF5_LIBRARIES         = /opt/intel/oneapi/intelpython/latest/lib/libhdf5.so;/usr/lib64/librt.so;/usr/lib64/libpthread.so;/opt/intel/oneapi/intelpython/latest/lib/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so
LIBXML2_INCLUDE_DIR    = /usr/include/libxml2
LIBXML2_LIBRARIES      = /usr/lib64/libxml2.so
FFTW_INCLUDE_DIR       =
FFTW_LIBRARIES         =
Boost_INCLUDE_DIR      = /usr/include
```
My **question** is:
Why dependencies like HDF5, Libxml2 and boot are not the ones that specified in the cmake script, and fftw is empty here? Thanks

**Comment by ye-luo** [comment]
Make a fresh build and provide all cmake printout.

**Comment by ye-luo** [comment]
Also `ls /home/ywang/code/hdf5-1.14.0/hdf5` what is the output

**Comment by YanyongW91** [comment]
here is the **cmake output**:
```
-- The C compiler identification is GNU 9.5.0
-- The CXX compiler identification is GNU 9.5.0
-- Check for working C compiler: /home/ywang/code/openmpi-4.1.5ing/bin/mpicc
-- Check for working C compiler: /home/ywang/code/openmpi-4.1.5ing/bin/mpicc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/ywang/code/openmpi-4.1.5ing/bin/mpicxx
-- Check for working CXX compiler: /home/ywang/code/openmpi-4.1.5ing/bin/mpicxx - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Defining the float point precision
   Base precision = double
   Full precision = double
-- CMAKE_BUILD_TYPE is RELEASE
-- Enable sanitizer ENABLE_SANITIZER=none
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Trying to figure out compiler options ....
-- C++ Compiler is identified by QMCPACK as : GNU
-- Looking for C++ include cstdio
-- Looking for C++ include cstdio - found
-- libstdc++/C++ compiler version compatibility check pass
-- C++17 standard library supported
-- QMC_SIMD_ALIGNMENT is set to 32
-- OpenMP taskloop functionality check pass
-- ENABLE_OMP_TASKLOOP is set to ON
-- Found MPI_CXX: /home/ywang/code/openmpi-4.1.5ing/bin/mpicxx (found version "3.1") 
-- Found MPI: TRUE (found version "3.1") found components: CXX 
-- Detected Open MPI. Setting bind-to options for thread affinity in MPIEXEC_PREFLAGS.
-- MPI runner MPIEXEC_EXECUTABLE : /opt/intel/oneapi/intelpython/latest/bin/mpiexec
-- MPIEXEC_NUMPROC_FLAG : -n
-- MPIEXEC_PREFLAGS : --bind-to;none
-- Tests run as : /opt/intel/oneapi/intelpython/latest/bin/mpiexec -n NUM_PROCS --bind-to none EXECUTABLE
-- MPI is enabled
-- Performing Test TEST_CXX_COMPILE_MAIN
-- Performing Test TEST_CXX_COMPILE_MAIN - Success
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Trying to find LAPACK from Intel MKL
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_intel_lp64.so;/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sequential.so;/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so;-lm;-ldl  
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- LAPACK linker flags: 
-- LAPACK libraries: /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_intel_lp64.so;/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sequential.so;/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so;-lm;-ldl;-lm;-ldl
-- Looking for Intel MKL library header files
-- MKL_INCLUDE: /opt/intel/oneapi/mkl/latest/include
-- MKL found: HAVE_MKL=TRUE, HAVE_MKL_FFTW3=TRUE
-- Selected vendor math library INTEL_VML
-- Setting up Intel MKL Vector Math Library (VML)
-- Looking for C++ include mkl_vml_functions.h
-- Looking for C++ include mkl_vml_functions.h - found
-- MKL VML found
-- SINCOS_INCLUDE : cmath
-- Performing Test HAVE_SINCOS
-- Performing Test HAVE_SINCOS - Success
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.7") 
-- Linking dynamic HDF5 library
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /opt/intel/oneapi/intelpython/latest/lib/libhdf5.so;/usr/lib64/librt.so;/usr/lib64/libpthread.so;/opt/intel/oneapi/intelpython/latest/lib/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so (found suitable version "1.10.2", minimum required is "1.10") found components: C 
-- Serial HDF5 library found
-- Using HDF5 non-scalable serial I/O code paths
CMake Warning at CMakeLists.txt:701 (message):
  MPI builds may have performance loss by not using parallel HDF5! (Safe to
  ignore for workstation builds).


-- Found Boost: /usr/include (found suitable version "1.66.0", minimum required is "1.61.0")  
-- Setting Boost_INCLUDE_DIRS=/usr/include
-- CUDA disabled
-- CUDA NVTX APIs disabled
-- VTune ittnotify APIs disabled
Project C_FLAGS:  -fopenmp -finline-limit=1000 -fstrict-aliasing -funroll-all-loops -Wno-deprecated -Werror=vla -ffast-math -march=native -O3 -DNDEBUG
Project CXX_FLAGS:  -fopenmp -foffload=disable -finline-limit=1000 -fstrict-aliasing -funroll-all-loops -Wno-deprecated -Wvla -Wcomment -Wmisleading-indentation -Wmaybe-uninitialized -Wuninitialized -Wreorder -Wno-unknown-pragmas -Wno-sign-compare -Wsuggest-override -ffast-math -march=native -O3 -DNDEBUG
Project INCLUDE_DIRECTORIES: /home/ywang/code/testing/new/qmcpack-3.16.0/build_gnu/src;/home/ywang/code/testing/new/qmcpack-3.16.0/src
Project EXE_LINKER_FLAGS:  
Project SHARED_LINKER_FLAGS:  
-- Found Git: /usr/bin/git (found version "2.27.0") 
-- QMC_SYMLINK_TEST_FILES = ON.  Using symbolic links for large test files may cause test failures if the build is installed on a separate filesystem from the source.
-- Found Python3: /opt/intel/oneapi/intelpython/latest/bin/python3.7 (found version "3.7.10") found components: Interpreter 
-- Unable to import PySCF python module. PySCF tests will not be run.
-- Unable to import GPAW python module. GPAW converter tests will not be run.
-- Did not find a patched Quantum ESPRESSO (QE) distribution with pw2qmcpack.x. QE tests will not be run.
-- Did not find RMG (rmg-cpu). RMG tests will not be run.
-- Ready to parse QMCPACK source tree
-- Adding integration tests for QMCPACK
Use --log-level=VERBOSE CMake option for details of which tests will be enabled.
Adding estimator tests for QMCPACK
Adding I/O tests for QMCPACK
QMC_DATA is not set. Performance tests will be skipped.
Adding system tests for QMCPACK
Traceback (most recent call last):
  File "/home/ywang/code/testing/new/qmcpack-3.16.0/tests/molecules/He_param/convert_vp_format.py", line 211, in <module>
    convert_from_text_to_hdf(fname_in, fname_out, args.complex)
  File "/home/ywang/code/testing/new/qmcpack-3.16.0/tests/molecules/He_param/convert_vp_format.py", line 179, in convert_from_text_to_hdf
    write_to_hdf(vp, fname_out, output_complex)
  File "/home/ywang/code/testing/new/qmcpack-3.16.0/tests/molecules/He_param/convert_vp_format.py", line 163, in write_to_hdf
    f.create_dataset("timestamp",data=np.array([vp.timestamp],dtype=object),dtype=h5py.string_dtype('ascii'))
AttributeError: module 'h5py' has no attribute 'string_dtype'
Adding example tests for QMCPACK
Adding Nexus tests
-- Configuring done
CMake Warning at src/io/hdf/tests/CMakeLists.txt:21 (add_executable):
  Cannot generate a safe runtime search path for target test_io_hdf5 because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/io/OhmmsData/tests/CMakeLists.txt:19 (add_executable):
  Cannot generate a safe runtime search path for target test_io_ohmmsdata
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/einspline/tests/CMakeLists.txt:25 (add_executable):
  Cannot generate a safe runtime search path for target test_einspline
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/Particle/tests/CMakeLists.txt:34 (add_executable):
  Cannot generate a safe runtime search path for target test_distance_table
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/Particle/tests/CMakeLists.txt:16 (add_executable):
  Cannot generate a safe runtime search path for target test_particle because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/Particle/Lattice/tests/CMakeLists.txt:16 (add_executable):
  Cannot generate a safe runtime search path for target test_lattice because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/Particle/LongRange/tests/CMakeLists.txt:16 (add_executable):
  Cannot generate a safe runtime search path for target test_longrange
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/Particle/ParticleIO/tests/CMakeLists.txt:16 (add_executable):
  Cannot generate a safe runtime search path for target test_particleio
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/Particle/ParticleBase/tests/CMakeLists.txt:16 (add_executable):
  Cannot generate a safe runtime search path for target test_particle_base
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/Utilities/tests/CMakeLists.txt:37 (add_executable):
  Cannot generate a safe runtime search path for target
  test_utilities_output_manager because files in some directories may
  conflict with libraries in implicit directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/Utilities/tests/CMakeLists.txt:16 (add_executable):
  Cannot generate a safe runtime search path for target test_utilities
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/Numerics/tests/CMakeLists.txt:34 (add_executable):
  Cannot generate a safe runtime search path for target test_numerics because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/spline2/tests/CMakeLists.txt:18 (add_executable):
  Cannot generate a safe runtime search path for target test_spline2 because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/QMCWaveFunctions/tests/CMakeLists.txt:169 (add_executable):
  Cannot generate a safe runtime search path for target
  test_wavefunction_trialwf because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/QMCWaveFunctions/tests/CMakeLists.txt:169 (add_executable):
  Cannot generate a safe runtime search path for target
  test_wavefunction_common because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/QMCWaveFunctions/tests/CMakeLists.txt:169 (add_executable):
  Cannot generate a safe runtime search path for target
  test_wavefunction_determinant because files in some directories may
  conflict with libraries in implicit directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/QMCWaveFunctions/tests/CMakeLists.txt:169 (add_executable):
  Cannot generate a safe runtime search path for target
  test_wavefunction_sposet because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/QMCWaveFunctions/tests/CMakeLists.txt:169 (add_executable):
  Cannot generate a safe runtime search path for target
  test_wavefunction_jastrow because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/QMCHamiltonians/tests/CMakeLists.txt:68 (add_executable):
  Cannot generate a safe runtime search path for target
  test_hamiltonian_force because files in some directories may conflict with
  libraries in implicit directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/QMCHamiltonians/tests/CMakeLists.txt:68 (add_executable):
  Cannot generate a safe runtime search path for target test_hamiltonian_ham
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/QMCHamiltonians/tests/CMakeLists.txt:68 (add_executable):
  Cannot generate a safe runtime search path for target
  test_hamiltonian_coulomb because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/QMCHamiltonians/tests/CMakeLists.txt:68 (add_executable):
  Cannot generate a safe runtime search path for target
  test_hamiltonian_ewald2d because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/Estimators/tests/CMakeLists.txt:70 (add_executable):
  Cannot generate a safe runtime search path for target test_estimators_mpi
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/Estimators/tests/CMakeLists.txt:44 (add_executable):
  Cannot generate a safe runtime search path for target test_estimators
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/QMCDrivers/tests/CMakeLists.txt:94 (add_executable):
  Cannot generate a safe runtime search path for target test_new_drivers
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/QMCDrivers/tests/CMakeLists.txt:118 (add_executable):
  Cannot generate a safe runtime search path for target test_drivers_mpi
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/QMCDrivers/tests/CMakeLists.txt:43 (add_executable):
  Cannot generate a safe runtime search path for target test_drivers because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/QMCApp/CMakeLists.txt:35 (add_executable):
  Cannot generate a safe runtime search path for target qmcpack because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/QMCTools/CMakeLists.txt:55 (add_executable):
  Cannot generate a safe runtime search path for target qmcfinitesize because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/QMCTools/CMakeLists.txt:36 (add_executable):
  Cannot generate a safe runtime search path for target
  qmc-extract-eshdf-kvectors because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/QMCTools/CMakeLists.txt:21 (add_executable):
  Cannot generate a safe runtime search path for target convert4qmc because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/QMCTools/CMakeLists.txt:46 (add_executable):
  Cannot generate a safe runtime search path for target convertpw4qmc because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/QMCTools/tests/CMakeLists.txt:23 (add_executable):
  Cannot generate a safe runtime search path for target test_tools because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libxml2.so.2] in /usr/lib64 may be hidden by files in:
      /opt/intel/oneapi/intelpython/latest/lib

  Some of these libraries may not be found correctly.


-- Generating done
-- Build files have been written to: /home/ywang/code/testing/new/qmcpack-3.16.0/build_gnu
```

**Comment by YanyongW91** [comment]
> Also `ls /home/ywang/code/hdf5-1.14.0/hdf5` what is the output

```
ywang@panghu:~/code/hdf5-1.14.0/hdf5$ ls
bin  include  lib  share
```

**Comment by ye-luo** [comment]
You are using MKL and thus, we prefer the fftw3 provided by MKL instead of standalone fftw3.
CMake insisted finding
```
-- Found HDF5: /opt/intel/oneapi/intelpython/latest/lib/libhdf5.so;/usr/lib64/librt.so;/usr/lib64/libpthread.so;/opt/intel/oneapi/intelpython/latest/lib/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so (found suitable version "1.10.2", minimum required is "1.10") found components: C 
```
It is unclear to me why this happened. There is an issue with hdf5 1.14.0 and 1.12.2.
https://github.com/spack/spack/issues/35893
1.12.0 or 1.12.1 should work.

**Comment by YanyongW91** [comment]
so I better use 1.12.0 or 1.12.1 for hdf5, and others need to change, right?
Also the issue you mentioned also occur for me when I try to install qmcpack on my laptop
