### ISSUE TITLE
Type error for AFQMC 

### ISSUE THREAD

**Issue by zohimchandani** [QMCPACK/qmcpack#4653]
Trying to run [this](https://qmcpack.readthedocs.io/en/develop/lab_afqmc.html#example-7-2x2x2-diamond-supercell:~:text=and%20DFT%20simulations.-,import%20h5py,-import%20numpy%0Aimport) code cell and getting this error below, any ideas? thanks 

```
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?5a840b1e-9464-4c8a-9de9-edd3e8f0f339)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 20
     18 mf = scf.KRHF(cell, kpts=kpts)
     19 mf.chkfile = 'scf.chk'
---> 20 mf.kernel()

File <string>:2, in kernel(self, dm0, **kwargs)

File /usr/local/lib/python3.10/dist-packages/pyscf/scf/hf.py:1697, in SCF.scf(self, dm0, **kwargs)
   1692 self.build(self.mol)
   1694 if self.max_cycle > 0 or self.mo_coeff is None:
   1695     self.converged, self.e_tot, \
   1696             self.mo_energy, self.mo_coeff, self.mo_occ = \
-> 1697             kernel(self, self.conv_tol, self.conv_tol_grad,
   1698                    dm0=dm0, callback=self.callback,
   1699                    conv_check=self.conv_check, **kwargs)
   1700 else:
   1701     # Avoid to update SCF orbitals in the non-SCF initialization
   1702     # (issue #495).  But run regular SCF for initial guess if SCF was
   1703     # not initialized.
   1704     self.e_tot = kernel(self, self.conv_tol, self.conv_tol_grad,
   1705                         dm0=dm0, callback=self.callback,
   1706                         conv_check=self.conv_check, **kwargs)[1]
...
-> 1465     return scipy.linalg.solve(a, b, sym_pos=True)
   1466 except numpy.linalg.LinAlgError:
   1467     if strict_sym_pos:

TypeError: solve() got an unexpected keyword argument 'sym_pos'


```

**Comment by jtkrogel** [comment]
This error is raised in PySCF and so is independent of QMCPACK or its tools.

The source of the issue appears to be a change in the API to scipy.linalg.solve.  `solve` no longer accepts `sym_pos` as an argument in the latest versions of scipy.  The issue you are facing is therefore an incompatibility between your PySCF and scipy versions.

**Comment by zohimchandani** [comment]
What versions of these packages is the code snippet in the documentation tested with?

**Comment by zohimchandani** [comment]
I was able to install scipy version 1.10.1 to overcome this issue. 

Running the second part of that [example](https://qmcpack.readthedocs.io/en/develop/lab_afqmc.html#example-7-2x2x2-diamond-supercell:~:text=from%20afqmctools.utils.linalg%20import%20get_ortho_ao) from here and got this error: 

```

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[4], line 1
----> 1 from afqmctools.utils.linalg import get_ortho_ao
      2 hcore = mf.get_hcore()
      3 fock = (hcore + mf.get_veff())

ModuleNotFoundError: No module named 'afqmctools'

```


Its not available to download as a pip package and does not come with the docker container either?

**Comment by prckent** [comment]
Take a look at https://qmcpack.readthedocs.io/en/develop/afqmc.html#afqmctools . You need to get the referenced path on your PYTHONPATH.

We don't have anything in pip (yet). The thought is to first improve the make install so that not only the python support files for AFQMC and real space QMC are installed, but also Nexus is fully setup.

**Comment by prckent** [comment]
I will close this issue since it appears fixed for now. Please reopen or create a new one for additional discussion on this topic.

**Comment by zohimchandani** [comment]
If I may keep it in 1 github issue, ill continue with this one. 

Continuing with example 7 [here](https://qmcpack.readthedocs.io/en/develop/lab_afqmc.html#example-7-2x2x2-diamond-supercell:~:text=results%20for%20methane%3F-,Example%207%3A%202x2x2%20Diamond%20supercell,-In%20this%20example), I have successfully created the `.chk` file. 

I can see the `pyscf_to_afqmc.py` script located here: 

```
root@gorby:~/qmcpack-develop/utils/afqmctools/bin# ls
afqmc_to_fcidump.py  fcidump_to_afqmc.py  kp_to_sparse.py  pyscf_to_afqmc.py  sparse_to_dense.py  test_afqmc_input.py  wfn_to_hdf5.py

```

but when I modify the command from [here](https://qmcpack.readthedocs.io/en/develop/lab_afqmc.html#example-7-2x2x2-diamond-supercell:~:text=mpirun%20%2Dn%208%20/path/to/qmcpack/utils/afqmctools/bin/pyscf_to_afqmc.py%20%2Di%20scf.chk%20%2Do%20afqmc.h5%20%2Dt%201e%2D5%20%2Dv%20%2Da) and run:


```
root@gorby:~# mpirun -n 4 /qmcpack-develop/utils/afqmctools/bin/pyscf_to_afqmc.py -i scf.chk -o afqmc.h5 -t 1e-5 -v -a
--------------------------------------------------------------------------
mpirun was unable to launch the specified application as it could not access
or execute an executable:

Executable: /qmcpack-develop/utils/afqmctools/bin/pyscf_to_afqmc.py
Node: gorby

while attempting to start process rank 0.
--------------------------------------------------------------------------
4 total processes failed to start

```

I located the `pyscf_to_afqmc.py` file and ran it and note that I dont have `mpi4py`. 

Could this be the issue or are the 2 not related?

**Comment by zohimchandani** [comment]
Update, I downloaded mpi4py and successfully created the checksome file required. When I run the command from [here](https://qmcpack.readthedocs.io/en/develop/lab_afqmc.html#example-7-2x2x2-diamond-supercell:~:text=mpirun%20%2Dn%208%20/path/to/qmcpack/utils/afqmctools/bin/pyscf_to_afqmc.py%20%2Di%20scf.chk%20%2Do%20afqmc.h5%20%2Dt%201e%2D5%20%2Dv%20%2Da), I get the following error:

```
root@gorby:~# mpirun -n 4 qmcpack-develop/utils/afqmctools/bin/pyscf_to_afqmc.py -i scf.chk -o afqmc.h5 -t 1e-5 -v -a
No protocol specified
 # Generating QMCPACK input from PYSCF checkpoint file.
 # git sha1: none
 # Date/Time: Wed Jul  5 15:42:10 2023
 # Working directory: /root
 # Generating Hamiltonian and wavefunction from pyscf cell object.
Traceback (most recent call last):
  File "/root/qmcpack-develop/utils/afqmctools/bin/pyscf_to_afqmc.py", line 165, in <module>
    main(sys.argv[1:])
  File "/root/qmcpack-develop/utils/afqmctools/bin/pyscf_to_afqmc.py", line 143, in main
    write_qmcpack(options.chk_file, options.hamil_file, options.thresh,
  File "/root/qmcpack-develop/utils/afqmctools/afqmctools/inputs/from_pyscf.py", line 38, in write_qmcpack
    scf_data = load_from_pyscf_chk(chkfile, orthoAO=ortho_ao)
  File "/root/qmcpack-develop/utils/afqmctools/afqmctools/utils/pyscf_utils.py", line 62, in load_from_pyscf_chk
    hcore = numpy.reshape(hcore,(-1,nao,nao))
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py", line 285, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 1 into shape (8,8)
Traceback (most recent call last):
  File "/root/qmcpack-develop/utils/afqmctools/bin/pyscf_to_afqmc.py", line 165, in <module>
    main(sys.argv[1:])
  File "/root/qmcpack-develop/utils/afqmctools/bin/pyscf_to_afqmc.py", line 143, in main
    write_qmcpack(options.chk_file, options.hamil_file, options.thresh,
  File "/root/qmcpack-develop/utils/afqmctools/afqmctools/inputs/from_pyscf.py", line 38, in write_qmcpack
    scf_data = load_from_pyscf_chk(chkfile, orthoAO=ortho_ao)
  File "/root/qmcpack-develop/utils/afqmctools/afqmctools/utils/pyscf_utils.py", line 62, in load_from_pyscf_chk
    hcore = numpy.reshape(hcore,(-1,nao,nao))
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py", line 285, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 1 into shape (8,8)
Traceback (most recent call last):
  File "/root/qmcpack-develop/utils/afqmctools/bin/pyscf_to_afqmc.py", line 165, in <module>
    main(sys.argv[1:])
  File "/root/qmcpack-develop/utils/afqmctools/bin/pyscf_to_afqmc.py", line 143, in main
    write_qmcpack(options.chk_file, options.hamil_file, options.thresh,
  File "/root/qmcpack-develop/utils/afqmctools/afqmctools/inputs/from_pyscf.py", line 38, in write_qmcpack
    scf_data = load_from_pyscf_chk(chkfile, orthoAO=ortho_ao)
  File "/root/qmcpack-develop/utils/afqmctools/afqmctools/utils/pyscf_utils.py", line 62, in load_from_pyscf_chk
    hcore = numpy.reshape(hcore,(-1,nao,nao))
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py", line 285, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 1 into shape (8,8)
Traceback (most recent call last):
  File "/root/qmcpack-develop/utils/afqmctools/bin/pyscf_to_afqmc.py", line 165, in <module>
    main(sys.argv[1:])
  File "/root/qmcpack-develop/utils/afqmctools/bin/pyscf_to_afqmc.py", line 143, in main
    write_qmcpack(options.chk_file, options.hamil_file, options.thresh,
  File "/root/qmcpack-develop/utils/afqmctools/afqmctools/inputs/from_pyscf.py", line 38, in write_qmcpack
    scf_data = load_from_pyscf_chk(chkfile, orthoAO=ortho_ao)
  File "/root/qmcpack-develop/utils/afqmctools/afqmctools/utils/pyscf_utils.py", line 62, in load_from_pyscf_chk
    hcore = numpy.reshape(hcore,(-1,nao,nao))
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py", line 285, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 1 into shape (8,8)
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[31221,1],0]
  Exit code:    1
--------------------------------------------------------------------------


```

This hints at an issue with the example in the docs. 

Can you test if this example works on your end please? Thanks 



(cc @davidev886)

**Comment by zohimchandani** [comment]
Update, the example above works fine on CPUs but fails with the error above on GPUs. 

(cc @davidev886)

**Comment by namehta4** [comment]
Hi All,

Is there any follow-up on this thread?

**Comment by prckent** [comment]
Q. Which version of PySCF are you using?

Since the tools on the QMCPACK side have not been touched in some time, a quick route to a solution might be going back to an older version of PySCF. This worked at some point since we did a workshop using them. These kinds issues have historically turned up when an API in either PySCF or a popular package have changed. Interestingly the failure occurs when trying to process a k-point, which presumably is not present for your neon atom run. => Likely a simple fix once isolated.

**Comment by namehta4** [comment]
Hi Paul,

Since part of this work will also be to use NVIDIA based code, it may require newer pySCF. Is there a way for me to request a workaround this issue?

Thank you!
Neil

**Comment by prckent** [comment]
Hi Neil - Sure, once pinned down we'll see about updating the script. Presumably the entries have changed between PySCF versions, which should be an easy fix. I would like for you to confirm that an older version works and that there are not other issues to get you up and running.

**Comment by prckent** [comment]
I will see about reproducing this locally -- I have some records suggesting PySCF v1.6.1 was OK. My guess is a change around v2 is involved.

**Comment by namehta4** [comment]
Hi Paul, in my original test case, I was using pySCF v 2.7.0. I tried installing qmcpack with pySCF v1.6.1 as recommended. There were several changes that are needed to install pySCF v 1.6.1 in the container itself. First, pySCF v1.6.1 requires numpy v1.25.2 (which breaks a lot of dependencies for the other packages in our workflow). Additionally, because pySCF v 1.6.1 does not come with libcint, it requires a separate install from source. However, even after getting preliminray things to install, I end up with the following error when trying to install pySCF v1.6.1
```
fatal error: pyscf/lib/np_helper/condense.c: No such file or directory
```
If needed, I could go down deeper inorder to complete the install, but the cap on the numpy version mentioned before does not allow lowering the pySCF version to be a valid alternative for us. Would there be a lesser painful way for me to get the example to work?

Thank you!
Neil

**Comment by prckent** [comment]
Thanks for trying. Will experiment with a spack install here.
